version: '3.3'
services:
  postgres:
    image: 'postgres:13'
    command: postgres --max_prepared_transactions=1000
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      POSTGRES_PASSWORD: mysecretpassword

    ports:
      - '5432:5432'
