version: '3.3'
services:
  api:
    build: ..
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
      - ..:/app/dtm
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    environment:
      IS_DOCKER: 1
    ports:
      - '9080:8080'
  mysql:
    image: 'mysql:5.7'
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /etc/timezone:/etc/timezone:ro
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    command:
      [
        '--character-set-server=utf8mb4',
        '--collation-server=utf8mb4_unicode_ci',
      ]
    ports:
      - '3306:3306'
